# Generated by Django 2.2.6 on 2019-10-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20191014_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.OneToOneField(null=True, on_delete=True, to='index.Author'),
        ),
    ]
