# Generated by Django 2.2.6 on 2019-10-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='index.Author'),
        ),
    ]
